### ISSUE TITLE
Postcodes

### ISSUE THREAD

**Issue by jjmedinaariza** [maczokni/crime_mapping#1]
I am rewriting the section on geocomputation and notice we geocode to "postcodes". All that section was a bit blurry since it kept talking about postcodes in different parts when clearly talking about different things (areas versus unit postcodes). I guess the practical example geocodes to the centroid of the unit postcode? Can you please confirm? Also, why did we do this? We may need to be explicit about the reasoning behind this.

**Comment by maczokni** [comment]
replaced this now with using the tidy geocoder packages, so should be resolved
