### ISSUE TITLE
rnaturalearth (ch 7)

### ISSUE THREAD

**Issue by maczokni** [maczokni/crime_mapping#8]
I use rnaturalearth in ch7 - we should generally introduce - should this be ch 5 cartography or appendix how to find spatial data?

**Comment by jjmedinaariza** [comment]
I would possible put the general intro to the package in the appendix

Juanjo Medina, PhD
Talentia Senior Distinguished Researcher
Department of Criminal Law and Crime Sciences
University of Seville
juanjomedina.con
________________________________
De: Reka Solymosi ***@***.***>
Enviado: martes, 6 de abril de 2021 9:34
Para: maczokni/crime_mapping ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [maczokni/crime_mapping] rnaturalearth (ch 7) (#8)


I use rnaturalearth in ch7 - we should generally introduce - should this be ch 5 cartography or appendix how to find spatial data?

**Comment by maczokni** [comment]
added an appendix on sourcing geo data which has a bit on rnaturalearth now
